# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: hairillusion_development
  pool: 5
  username: root
  password: hairillusion
  host: 127.0.0.1

